### ISSUE TITLE
getCampaign()

### ISSUE THREAD

**Issue by kpiyush1095** [talon-one/maven-artefacts#5]
public void getCampaign() throws IOException, ApiException {
        Integer pageSize = 0;
        Integer skip = 0;
        String sort = "";
        String campaignState="";
        String name="";
        Integer campaignGroupId=0;
        String tags="";

        InlineResponse2002 inlineResponse2002=managementApi.getCampaigns(3, pageSize, skip, sort,
                campaignState, name, tags, createdBefore, createdAfter, campaignGroupId);
        System.out.println( inlineResponse2002.getData());
    }

I am using this method but getting null in getData(). Please help.

**Comment by altJake** [comment]
Hello @kpiyush1095 and thank you very much for sending your issue.

I can see that you are using a slightly customized version of [the code sample](https://github.com/talon-one/TalonOneJavaSdk/blob/master/docs/ManagementApi.md#getCampaigns) in the JavaSDK repository.

Unfortunately, some of these examples are trying to be too helpful, and show a _potentially_ full utilization of the functions arguments. Those examples use actual sample values (i.e. numbers for Integer arguments and so on) and therefore they are very likely to confuse the user into providing all of them when calling the function. However, most of them are optional, and when you are not sure about the value to provide, I'd recommend passing on a `null` value. Our API will then use the default values for these parameters for you, which will as well, I believe, resolve the issue in your report.

In practice, from the code sample above I assume that what happens is that providing some of the arguments with valid "lookup" values, such as an empty strings, results in an empty response from our server.

I can also recommend you to have a look at our API reference in the documentation website, specifically for this particular requests you can see the specification [here](https://docs.talon.one/management-api#tag/Campaigns/operation/getCampaigns), which I hope so help with understanding the meaning of each argument and it's impact on the request.

How that you'll find all this helpful! I'm going to keep the issue open until you confirm that the issue was resolved.

Thank you very much again for your question, and please don't hesitate to follow up with any questions that you might have.
